[toolchain]
solana_version = "2.1.0"

[features]
seeds = false
skip-lint = false

[programs.devnet]
yieldpilot = "8c7Boyk91MWkn5jabf5CnYD8DrG6p4hYm9eDdAAWXEKH"

[programs.mainnet]
yieldpilot = "3tAEmHXZ51YVLe9ts8b9cMcgQPgaSamLxLtxR31VpREi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
deploy = "ts-node scripts/deploy.ts"
