import * as anchor from "@coral-xyz/anchor";
import { Connection, Keypair, PublicKey } from "@solana/web3.js";
import fs from "fs";
import os from "os";
import path from "path";
import { logger } from "./logger";

// ─────────────────────────────────────────────────────────────────────────────
// Types mirroring the on-chain Vault account
// ─────────────────────────────────────────────────────────────────────────────

export interface VaultState {
  admin: PublicKey;
  mint: PublicKey;
  vaultTokenAccount: PublicKey;
  sharesMint: PublicKey;
  treasury: PublicKey;
  gateMint: PublicKey;
  totalDeposits: anchor.BN;
  totalShares: anchor.BN;
  perfFeeBps: anchor.BN;
  autoCompound: boolean;
  autoRebalance: boolean;
  paused: boolean;
  lastCompoundTs: anchor.BN;
  bump: number;
  authorityBump: number;
  protocolCount: number;
  tvlCap: anchor.BN;
  name: string;
  protocols: {
    kind: any;
    externalState: PublicKey;
    vaultReceiptAccount: PublicKey;
    targetBps: anchor.BN;
    deployedBalance: anchor.BN;
    label: string;
  }[];
}

// ─────────────────────────────────────────────────────────────────────────────
// SolanaClient
// ─────────────────────────────────────────────────────────────────────────────

export class SolanaClient {
  public connection: Connection;
  public keeper: Keypair;
  public program: anchor.Program;

  constructor() {
    const rpcUrl = process.env.RPC_URL || "https://api.devnet.solana.com";
    this.connection = new Connection(rpcUrl, {
      commitment: "confirmed",
      confirmTransactionInitialTimeout: 60_000,
    });

    // Load keeper keypair
    const keypairPath = (process.env.KEEPER_KEYPAIR_PATH || "~/.config/solana/id.json")
      .replace("~", os.homedir());
    const raw = JSON.parse(fs.readFileSync(path.resolve(keypairPath), "utf8"));
    this.keeper = Keypair.fromSecretKey(Uint8Array.from(raw));

    // Build Anchor provider
    const wallet = new anchor.Wallet(this.keeper);
    const provider = new anchor.AnchorProvider(this.connection, wallet, {
      commitment: "confirmed",
      preflightCommitment: "confirmed",
    });
    anchor.setProvider(provider);

    // Load IDL (generated by `anchor build`, placed in src/idl/)
    const idlPath = path.resolve(__dirname, "idl/yieldpilot.json");
    const idl = JSON.parse(fs.readFileSync(idlPath, "utf8"));
    const programId = new PublicKey(process.env.PROGRAM_ID!);
    // Anchor 0.31: Program constructor takes (idl, provider) — programId read from IDL
    this.program = new anchor.Program(idl, provider);

    logger.info("SolanaClient initialized", {
      rpc: rpcUrl,
      keeper: this.keeper.publicKey.toBase58(),
      program: programId.toBase58(),
    });
  }

  // ── Vault fetching ────────────────────────────────────────────────────────

  async fetchVault(vaultAddress: string): Promise<VaultState> {
    const pubkey = new PublicKey(vaultAddress);
    const vault = await (this.program.account as any)["vault"].fetch(pubkey) as VaultState;
    return vault;
  }

  async fetchAllVaults(): Promise<{ address: string; state: VaultState }[]> {
    const addresses = (process.env.VAULT_ADDRESSES || "")
      .split(",")
      .map(s => s.trim())
      .filter(Boolean);

    const results = await Promise.allSettled(
      addresses.map(async addr => ({
        address: addr,
        state: await this.fetchVault(addr),
      }))
    );

    return results
      .filter((r): r is PromiseFulfilledResult<{ address: string; state: VaultState }> =>
        r.status === "fulfilled"
      )
      .map(r => r.value);
  }

  // ── Transaction helpers ───────────────────────────────────────────────────

  /** Send a transaction with exponential backoff retry */
  async sendWithRetry(
    txFn: () => Promise<string>,
    label: string,
    maxAttempts = 3
  ): Promise<string | null> {
    for (let attempt = 1; attempt <= maxAttempts; attempt++) {
      try {
        const sig = await txFn();
        logger.info(`${label} confirmed`, { signature: sig, attempt });
        return sig;
      } catch (err: any) {
        const isLast = attempt === maxAttempts;
        logger.warn(`${label} failed (attempt ${attempt}/${maxAttempts})`, {
          error: err.message,
        });
        if (!isLast) {
          await sleep(1000 * 2 ** attempt); // 2s, 4s, 8s
        }
      }
    }
    logger.error(`${label} failed after ${maxAttempts} attempts`);
    return null;
  }

  // ── Keeper actions ────────────────────────────────────────────────────────

  async rebalance(
    vaultAddress: string,
    newAllocations: number[]
  ): Promise<string | null> {
    const vaultPubkey = new PublicKey(vaultAddress);
    return this.sendWithRetry(
      () =>
        this.program.methods
          .rebalance(newAllocations.map(n => new anchor.BN(n)))
          .accounts({
            admin: this.keeper.publicKey,
            vault: vaultPubkey,
          })
          .rpc(),
      `rebalance(${vaultAddress.slice(0, 8)}...)`
    );
  }

  async compound(vaultAddress: string): Promise<string | null> {
    const vaultPubkey = new PublicKey(vaultAddress);
    return this.sendWithRetry(
      () =>
        this.program.methods
          .compound()
          .accounts({
            admin: this.keeper.publicKey,
            vault: vaultPubkey,
          })
          .rpc(),
      `compound(${vaultAddress.slice(0, 8)}...)`
    );
  }

  // ── Utility ───────────────────────────────────────────────────────────────

  async getKeeperBalance(): Promise<number> {
    const lamports = await this.connection.getBalance(this.keeper.publicKey);
    return lamports / 1e9;
  }
}

function sleep(ms: number) {
  return new Promise(resolve => setTimeout(resolve, ms));
}
