// Generate the Raydium harness start script with tick arrays taken from the LIVE pool.
//
// The cloned pool keeps trading on mainnet, so a hardcoded --clone list of tick arrays goes
// stale: the position lands outside every cloned array and either fails to open or opens
// out-of-range and earns nothing. That is how the previous Raydium suite "passed" while
// proving nothing. Regenerate this before each run.
const fs = require("fs");
const { Connection, PublicKey } = require("@solana/web3.js");

const MEM = "C:/Users/lloyd/.claude/projects/C--Users-lloyd-OneDrive-Documents-yield-claude-code/memory/project_yieldpilot_critical_keys.md";
const RPC = fs.readFileSync(MEM, "utf8").match(/NEW_MAINNET_RPC_URL:\s*(\S+)/)[1];

const CLMM = new PublicKey("CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK");
const POOL = new PublicKey("3ucNos4NbumPLZNWztqGHNFFgkHeRMBQAVemeeomsUxv");
const beI32 = (n) => { const b = Buffer.alloc(4); b.writeInt32BE(n); return b; };

// Static pool infrastructure — these do not move.
const BASE = [
  "3h2e43PunVA5K34vwKCLHWhZF4aZpyaC9RmxvshGAQpL", // amm config
  "3ucNos4NbumPLZNWztqGHNFFgkHeRMBQAVemeeomsUxv", // pool state
  "4ct7br2vTPzfdmY3S5HLtTxcGSBfn6pnw98hsS6v359A", // token vault 0
  "5it83u57VRrVgc51oNV19TTmAJuffPx5GtGwQr7gQNUo", // token vault 1
  "3Y695CuQ8AP4anbwAqiEBeQF9KxqHFr8piEwvw3UePnQ", // observation state
  "So11111111111111111111111111111111111111112",
  "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
  // Reward machinery. decrease_liquidity collects rewards in the SAME instruction and
  // takes [reward_vault, recipient] as remaining accounts, so the RAY mint must exist
  // locally or creating the recipient ATA fails with IncorrectProgramId. Dropping these
  // from the clone list broke the suite at step 4 on 2026-07-24.
  "HsBUudV9Y2Z2dJTieWFgK3zhrpX4ELvnfHcAwSBVqDGX", // RAY reward vault
  "4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R", // RAY mint
  // Pool support accounts carried over from the original hand-written script.
  "77PUSkkMGNnoQ3nQ6az9fFJEra2TPJJGBMdPKBShQ8rg",
  "6mXy1V1B5b3xZLoetYykGxuib8Zb2MXBnYJaLkexgz2o",
  "HVfrwPyUmRi7B5KuJi7A8FxcgriKeEnMJ6bJH7UmHWNw",
  "2nBm3kwgzmHhrMwHYcRsz54kgyqzLXjgzQBvCfgBt3bo",
  "Dx7u93Y7Zo5hGSa9fXCTMWSwAi9PiBi2hkSgq9Le3x2A",
];

(async () => {
  const c = new Connection(RPC, { commitment: "confirmed" });
  const d = (await c.getAccountInfo(POOL)).data;
  let o = 8 + 1 + 32 * 7 + 1 + 1;
  const spacing = d.readUInt16LE(o);
  o += 2 + 16 + 16;
  const tick = d.readInt32LE(o);
  const SPAN = 60 * spacing;
  const aS = (t) => Math.floor(t / SPAN) * SPAN;

  const arrays = [];
  for (let k = -3; k <= 3; k++) {
    const s = aS(tick) + k * SPAN;
    const [pda] = PublicKey.findProgramAddressSync(
      [Buffer.from("tick_array"), POOL.toBuffer(), beI32(s)], CLMM);
    if (await c.getAccountInfo(pda)) arrays.push({ s, pda: pda.toBase58() });
  }

  const L = [];
  L.push("#!/bin/bash");
  L.push("# GENERATED by gen_ray_start.js — do not hand-edit the tick array list.");
  L.push(`# Live pool tick ${tick}, spacing ${spacing}, ${SPAN} ticks/array.`);
  L.push(`# Cloned arrays: ${arrays.map(a => a.s).join(", ")}`);
  L.push("export PATH=$HOME/.local/share/solana/install/active_release/bin:$PATH");
  L.push("cd /root/localval || exit 1");
  L.push('SO="${1:?need .so path}"');
  L.push('LEDGER="${2:-/root/localval/ledger_ray2}"');
  L.push(`RPC="${RPC}"`);
  L.push("exec solana-test-validator \\");
  L.push('  --url "$RPC" \\');
  L.push('  --bpf-program 8c7Boyk91MWkn5jabf5CnYD8DrG6p4hYm9eDdAAWXEKH "$SO" \\');
  L.push("  --clone-upgradeable-program CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK \\");
  L.push("  --clone-upgradeable-program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s \\");
  for (const a of BASE) L.push(`  --clone ${a} \\`);
  for (const a of arrays) L.push(`  --clone ${a.pda} \\`);
  L.push("  --account 5gXt4YTqgDyzfL4zMErMRGB47gi1N6VAywowAsCAGEac /root/localval/usdc_ata.json \\");
  L.push('  --ledger "$LEDGER" \\');
  L.push("  --reset --quiet");

  fs.writeFileSync("start_ray2.sh", L.join("\n") + "\n");
  console.log(`live tick ${tick} | spacing ${spacing} | span ${SPAN}`);
  console.log(`cloning ${arrays.length} tick arrays: ${arrays.map(a => a.s).join(", ")}`);
  console.log("wrote start_ray2.sh");
  fs.writeFileSync("ray_tick.json", JSON.stringify({ tick, spacing, SPAN }, null, 1));
})().catch(e => { console.error("ERR", e.message); process.exit(1); });
